
service: serverless-image-recognition

plugins:
  # - serverless-offline 

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - rekognition:*
      - s3:*
    Resource: "*"

functions:
  tweet:
    handler: handler.tweet
    events:
      - http:
          method: get
          path: /tweet
      - http:
          method: post
          path: /verify
  verify:
    handler: handler.verify
    events:
      - http:
          method: get
          path: /verify
  testS3:
    handler: handler.testS3
    events:
      - http:
          method: get
          path: /testS3
  processImage:
    handler: handler.processImage
    events:
      - http:
          method: get
          path: /processImage

